[package]
name = "day-4"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-utils = { version = "0.1.0", path = "../aoc-utils" }
nom = "7.1.3"
rayon = "1.10.0"

[dev-dependencies]
test-case = "3.3.1"
