[package]
name = "day-7"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-utils = { version = "0.1.0", path = "../aoc-utils" }
itertools = "0.13.0"
nom = "7.1.3"

[dev-dependencies]
test-case = "3.3.1"
