[package]
name = "day-3"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-utils = { version = "0.1.0", path = "../aoc-utils" }
nom = "7.1.3"
regex = "1.11.1"

[dev-dependencies]
test-case = "3.3.1"
